// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart'; 
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // case TargetPlatform.windows:
      //   return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOFDMJkZVP2pbk8D_ViJqlZJFezzq5S8',
    appId: '1:992729470612:web:4cc139628ef7d057d0c681',
    messagingSenderId: '992729470612',
    projectId: 'tourify-222',
    authDomain: 'tourify-222.firebaseapp.com',
    storageBucket: 'tourify-222.firebasestorage.app',
    measurementId: 'G-JLN1GZCF71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOFDMJkZVP2pbk8D_ViJqlZJFezzq5S8',
    appId: '1:992729470612:android:0be7dfc054bf786ad0c681',
    messagingSenderId: '992729470612',
    projectId: 'tourify-222',
    storageBucket: 'tourify-222.firebasestorage.app',
    measurementId: 'G-JLN1GZCF71',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOFDMJkZVP2pbk8D_ViJqlZJFezzq5S8',
    appId: '1:992729470612:ios:fb98a2df64ab925cd0c681',
    messagingSenderId: '992729470612',
    projectId: 'tourify-222',
    storageBucket: 'tourify-222.firebasestorage.app',
    iosBundleId: 'com.example.tourify',
    measurementId: 'G-JLN1GZCF71',
  );

  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'AIzaSyCOFDMJkZVP2pbk8D_ViJqlZJFezzq5S8',
  //   appId: 'blank rekhe dilam',
  //   messagingSenderId: '992729470612',
  //   projectId: 'tourify-222',
  //   authDomain: 'tourify-222.firebaseapp.com',
  //   storageBucket: 'tourify-222.firebasestorage.app',
  //   measurementId: 'G-JLN1GZCF71',
  // );
}